use [Selero]

select * from ManufacturerFileFormat
select * from ManufacturerFileFormatColumn where ManufacturerFileFormatUID=1

-- truncate table ManufacturerFileFormat
-- truncate table ManufacturerFileFormatColumn

/*
insert into ManufacturerFileFormat (Name,Active,Delimiter,Header,CreatedMachine,CreatedApp,CreatedDate,CreatedBy,UpdatedMachine,UpdatedApp,UpdatedDate,UpdatedBy)
values
	('abbvie',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|IMBRUVICA_STATUS|RETAIL_TRANSMISSION_DATE|IMBRUVICA_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('amgen',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('bausch',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('biogen',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('boehringer_ingelheim',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|LDN_STATUS|RETAIL_TRANSMISSION_DATE|LDN_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('bristol_myers_squibb',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|REMS_STATUS|CAMZYOS_STATUS|RETAIL_TRANSMISSION_DATE|REMS_TRANSMISSION_DATE|CAMZYOS_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('exelixis',0,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|CABOMETYX_STATUS|COMETRIQ_STATUS|CABOMETYX_TRANSMISSION_DATE|COMETRIQ_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('gilead',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('glaxosmithkline',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('merck',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('novo_nordisk',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|LDN_STATUS|RETAIL_TRANSMISSION_DATE|LDN_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('pfizer',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|DON_STATUS|RETAIL_TRANSMISSION_DATE|DON_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('johnson_n_johnson',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|PAH_STATUS|RETAIL_TRANSMISSION_DATE|PAH_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('sanofi',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,('ucb',1,'|','340B_ID|PHARMACY_ID|DEA|PHARMACY_NAME|PHARMACY_ADDRESS_1|PHARMACY_ADDRESS_2|PHARMACY_ADDRESS_3|PHARMACY_CITY|PHARMACY_STATE|PHARMACY_ZIP|RETAIL_STATUS|RETAIL_TRANSMISSION_DATE',
	HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

-- dbcc CHECKIDENT (ManufacturerFileFormat, NORESEED)
-- dbcc CHECKIDENT (ManufacturerFileFormat, RESEED, 1)
*/

/*
insert into ManufacturerFileFormatColumn values
	(1,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,12,'IMBRUVICA_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,13,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(1,14,'IMBRUVICA_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(2,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(2,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(3,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(3,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(4,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(4,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(5,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,12,'LDN_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,13,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(5,14,'LDN_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(6,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,12,'REMS_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,13,'CAMZYOS_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,14,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,15,'REMS_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(6,16,'CAMZYOS_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(7,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,12,'CABOMETYX_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,13,'COMETRIQ_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,14,'CABOMETYX_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(7,15,'COMETRIQ_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(8,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(8,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(9,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(9,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(10,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(10,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(11,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,12,'LDN_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,13,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(11,14,'LDN_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(12,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,12,'DON_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,13,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(12,14,'DON_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(13,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,12,'PAH_STATUS',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,13,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(13,14,'PAH_TRANSMISSION_DATE',null,HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(14,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(14,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

insert into ManufacturerFileFormatColumn values
	(15,1,'340B_ID','ID340B',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,2,'PHARMACY_ID','PharmacyID',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,3,'DEA','DEA',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,4,'PHARMACY_NAME','PharmacyName',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,5,'PHARMACY_ADDRESS_1','PharmacyAddress1',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,6,'PHARMACY_ADDRESS_2','PharmacyAddress2',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,7,'PHARMACY_ADDRESS_3','PharmacyAddress3',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,8,'PHARMACY_CITY','PharmacyCity',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,9,'PHARMACY_STATE','PharmacyState',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,10,'PHARMACY_ZIP','PharmacyZip',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,11,'RETAIL_STATUS','RetailStatus',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())
	,(15,12,'RETAIL_TRANSMISSION_DATE','RetailTransmissionDate',HOST_NAME(),'Studio',GETDATE(),SUSER_NAME(),HOST_NAME(),'Studio',GETDATE(),SUSER_NAME())

-- dbcc CHECKIDENT (ManufacturerFileFormatColumn, NORESEED)
-- dbcc CHECKIDENT (ManufacturerFileFormatColumn, RESEED, 1)
*/